apiVersion: apps/v1
kind: Deployment
metadata:
  name: generate-soal-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generate-soal-service
  template:
    metadata:
      labels:
        app: generate-soal-service
    spec:
      containers:
      - name: generate-soal-service
        image: your-generate-soal-service-image:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: "postgres://your_db_user:your_db_password@postgres:5432/your_db_name"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: generate-soal-service
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: generate-soal-service